<template>
  <div id="app" class="container">

    <!-- nav -->
    <nav class="navbar is-transparent">
      <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="#">HestiaCP/Config</a>
        <div class="navbar-burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-start">
          <span class="navbar-item">Home</span>
        </div>
      </div>
    </nav>

    <!-- container -->
    <div class="columns is-multiline">
      <div class="column is-8">
        <div class="columns is-multiline">

          <div class="column is-4 p-2" v-for="item in this.$data.config">
            <div class="card py-0">
              <header class="card-header is-danger">
                <span class="card-header-title"> <o-checkbox v-model="item.selected">{{ item.name }}</o-checkbox></span>
              </header>
              <div class="card-content">
                <div class="columns is-multiline">
                  <div class="column is-12">
                    <p>{{ item.desc }}</p>
                  </div>
                  <div class="column is-12">
                    <p>Default: <em>{{ item.standard }}</em></p>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="column is-4">
        <div class="columns is-multiline">
          <div class="column is-12">
            <button class="button is-success is-fullwidth" @click="generateString">Generate HestiaCP install string</button>
          </div>
          <div class="column is-12">
            <div class="message is-info">
              <div class="message-header">INSTRUCTIONS - how to easily install HestiaCP</div>
              <div class="message-body">
                <div class="content">
                  <p>Log in to your server as root, either directly or via SSH: <code>ssh root@your.server</code></p>
                  <p>Download the installation script:</p>
                  <input class="input" value="wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh"/>
                  <br/>
                  <br/>
                  <p>Then run the following command, autogenerated based on the options you have chosen above:</p>
                  <textarea class="textarea" v-model="installstr"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<script>
import hestia from "./data/hestia";
import oruga from "@oruga-ui/oruga-next/dist/oruga.mjs";

export default {
  name: 'App',
  data() {
    return {
      pageloader: false,
      hestia_wget: "wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh",
      hestia_install: "sudo bash hst-install.sh",
      installstr: "",
      config: hestia
    }
  },
  methods: {
    generateString() {
      let installstr = [];

      this.$data.config.forEach(value => {
        let item = (JSON.parse(JSON.stringify(value)));

        if (item.selected) {
          installstr.push(item.param)
        }

      })

      this.$data.installstr = this.$data.hestia_install + " " + installstr.join(" ");
    }
  },
  mounted() {
    this.generateString()
  }
}
</script>
