<template>
  <div id="app" class="container">

    <!-- nav -->
    <nav class="navbar is-transparent mb-5">
      <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="/">HestiaCP&utdot;Command Creator</a>
        <div class="navbar-burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-start">
          <a href="https://hestiacp.com/" class="navbar-item">hestiacp.com</a>
          <a href="https://docs.hestiacp.com/getting_started.html" class="navbar-item">docs.hestiacp.com</a>
        </div>
        <div class="navbar-end">
          <a href="https://github.com/turbopixel/HestiaCP-Command-Creator" class="navbar-item">GitHub</a>
          <a href="https://mastodon.social/@turbopioxel" class="navbar-item">Mastodon</a>
        </div>
      </div>
    </nav>

    <!-- container -->
    <div class="columns is-multiline">
      <div class="column is-8">
        <div class="columns is-multiline">

          <div class="column is-4" v-for="item in this.$data.config">
            <div class="card p-0">
              <header class="card-header is-danger">
                <span class="card-header-title"> <o-checkbox v-model="item.selected">{{ item.name }}</o-checkbox></span>
              </header>
              <div class="card-content">
                <div class="columns is-multiline">
                  <div class="column is-12">
                    <p>{{ item.desc }}</p>
                  </div>
                  <div class="column is-12" v-if="item.textField">
                    <input type="text" class="input" v-model="item.text">
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="column is-4">
        <div class="columns is-multiline">
          <div class="column is-12">
            <button class="button is-success is-fullwidth" @click="generateString">Generate HestiaCP install string</button>
          </div>
          <div class="column is-12" v-if="installstr">
            <div class="message is-info">
              <div class="message-header">How to easily install HestiaCP</div>
              <div class="message-body">
                <div class="content">
                  <p>Log in to your server as root, either directly or via SSH: <code>ssh root@your.server</code></p>
                  <o-field label="Download the installation script:">
                    <o-input type="input" class="is-fullwidth input" :expanded="true" v-model="hestia_wget"/>
                  </o-field>
                  <br/>
                  <p>Then run the following command, autogenerated based on the options you have chosen above:</p>
                  <textarea class="textarea" rows="8" v-model="installstr"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<script>
import hestia from "./data/hestia";
import oruga from "@oruga-ui/oruga-next/dist/oruga.mjs";

export default {
  name: 'App',
  data() {
    return {
      pageloader: false,
      hestia_wget: "wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh",
      hestia_install: "sudo bash hst-install.sh",
      installstr: "",
      config: hestia
    }
  },
  methods: {
    generateString() {
      let installstr = [];

      this.$data.config.forEach(value => {
        let item = (JSON.parse(JSON.stringify(value)));

        if (item.textField && item.selected) {
          if(item.text.length >= 2){
            installstr.push(item.param + " '" + item.text + "'")
          }
        } else if(!item.textField) {
          if (item.param.includes("force")) {
            item.selected ? installstr.push(item.param) : ""
          } else {
            installstr.push(item.param + (item.selected ? " yes" : " no"))
          }
        }

      })

      this.$data.installstr = this.$data.hestia_install + " " + installstr.join(" ");
    }
  },
  mounted() {
  }
}
</script>
